import type { Metadata } from "next";
import { Inter, Karantina } from "next/font/google";

import "./globals.css";
import "./style.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const karantina = Karantina({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-karantina",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${karantina.variable} text-primary font-primary`}
      >
        {children}
      </body>
    </html>
  );
}
